server:
  address: ":8080"
routes:
  - path: "/"
    handler: "IndexHandler"
    methods:
      - "GET"
    auth_required: false
  - path: "/about"
    handler: "AboutHandler"
    methods:
      - "GET"
    auth_required: false
  - path: "/page/{name}"
    handler: "PageHandler"
    methods:
      - "GET"
    auth_required: false
  - path: "/admin/login"
    handler: "LoginHandler"
    methods:
      - "GET"
      - "POST"
    auth_required: false
  - path: "/admin/dashboard"
    handler: "DashboardHandler"
    methods:
      - "GET"
    auth_required: true
  - path: "/admin"
    handler: "AdminRedirectHandler"
    methods:
      - "GET"
    auth_required: true
database:
  type: "sqlite"
  dsn: "./data/gemini.db"
auth:
  session_key: "a-very-secret-key" # TODO: Change this in a real application
  csrf_key: "7f4b6cc6ca4141e293a2e66756b96b85"
static:
  url_prefix: "/static/"
  dir: "static"
